
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


spring.datasource.url=jdbc:postgresql://dpg-cq19dhlds78s73djsfm0-a.frankfurt-postgres.render.com/moviedb_hi38
spring.datasource.username=root
spring.datasource.password=5qS7Nyc1kN0dTQKI8f51FoGhTcOqC67m
spring.datasource.driver-class-name=org.postgresql.Driver



springdoc.swagger-ui.path=/docs
